Первая попытка
AbdullinAM/programming-task1-2022 pull request #2
Opened 2022-02-10 21:47 UTC by rsmolentsev

2022-02-11 08:37 UTC, AbdullinAM requested changes

2022-02-11 08:37 UTC, AbdullinAM commented on app/src/main/java/programming/task1/App.java
> +    String address;
В задании явно сказано, что адес состоит из улицы, номера дома и номаре квартиры. Хранить все это в строке не очень удобно. Что делать, например, если вы захотите узнать какой номер у данного адреса? Каждый раз парсить строку не очень удобно. Лучше для адреса завести отдельную сущность

2022-02-11 08:37 UTC, AbdullinAM commented on app/src/main/java/programming/task1/App.java
> +    String address;
И кажется что адрес не должен быть частью класса `Person`

2022-02-11 08:37 UTC, AbdullinAM commented on app/src/main/java/programming/task1/App.java
> +    public ArrayList<String> addPerson(ArrayList<String> addresses, String name, String address) {
Кажется что вы не совсем правильно поняли задание. Вы должны реализовать адресную книгу, которая хранит в себе список людей, и адресов по которым эти люди живут. Методы должны изменять внутреннее состояние данного объекта или получать это состояние. 

Сейчас же у вас просто набор методов для модификации списка строк, который хранится где-то извне.

2022-02-11 08:52 UTC, rsmolentsev commented on app/src/main/java/programming/task1/App.java
> +    String address;
Видимо, задание действительно не так понял, как предполагалось. Спасибо, буду исправлять.

2022-02-11 09:02 UTC, AbdullinAM commented on app/src/main/java/programming/task1/App.java
> +    String address;
Если до сих пор непонятно что нужно делать &mdash; можем подробнее поговорить на паре

2022-02-16 08:27 UTC, AbdullinAM requested changes

2022-02-16 08:27 UTC, AbdullinAM commented on app/src/main/java/programming/task1/App.java
> +        for (String key : addresses.keySet()) {
Подумайте есть ли более эффективный способ получения значения по ключу

2022-02-16 08:27 UTC, AbdullinAM commented on app/src/main/java/programming/task1/App.java
> +    private String home;
Правильно ли хранить номер дома и номер квартиры в виде строки?

2022-02-16 08:27 UTC, AbdullinAM commented on app/src/main/java/programming/task1/App.java
> +
Название класса стоило бы поменять, чтобы оно больше соответствовало тому что вы делаете

2022-02-16 08:27 UTC, AbdullinAM commented on app/src/main/java/programming/task1/App.java
> +        for (String key : addresses.keySet()) {
Обход ключей в HashMap никак не детерминирован. В зависимости от того как лягут хеши, ключи могут располагаться в мапе в разном порядке. Соответственно, в результирующем списке у вас элементы могут располагаться в разном порядке

2022-02-16 08:27 UTC, AbdullinAM commented on app/src/test/java/programming/task1/AppTest.java
> +        assertEquals(List.of(new String[]{"Анненко", "Михайлов", "Вишняков"}), book.getNamesByStreet(address));
Из-за того что `getNamesByStreet` никак не гарантирует вам порядка элементов, тест падает при запуске на других машинах

2022-02-17 08:25 UTC, AbdullinAM approved these changes

2022-02-17 08:27 UTC, AbdullinAM requested changes

2022-02-17 08:27 UTC, AbdullinAM commented on app/src/main/java/programming/task1/AddressBook.java
> +    private final Map<String, Address> addresses = new LinkedHashMap<>();
Расскажите в чем разница между HashMap и LinkedHashMap и зачем вам понадобилось это изменение

2022-02-17 08:27 UTC, AbdullinAM commented on app/src/test/java/programming/task1/AddressBookTest.java
> +        List<String> expected = new ArrayList<>(List.of(new String[]{"Анненко", "Михайлов", "Вишняков"}));
Зачем результат `List.of` еще раз упаковывать в список?

2022-02-17 08:44 UTC, rsmolentsev commented on app/src/main/java/programming/task1/AddressBook.java
> +    private final Map<String, Address> addresses = new LinkedHashMap<>();
У HashMap не предусмотрено упорядочивание ключей, в отличие от LinkedHashMap. Понадобилось это изменение для того, чтобы ключи лежали в нужном мне порядке (то есть по мере добавления пары человек-адрес)

2022-02-17 08:58 UTC, rsmolentsev commented on app/src/test/java/programming/task1/AddressBookTest.java
> +        List<String> expected = new ArrayList<>(List.of(new String[]{"Анненко", "Михайлов", "Вишняков"}));
Исправлю в следующем коммите

2022-02-17 11:02 UTC, AbdullinAM approved these changes

2022-02-17 11:02 UTC, AbdullinAM commented
Задание принято с оценкой 5

2022-02-17 11:02 UTC, closed without merging