Ким В. А. 3530901/10006
AbdullinAM/programming-task1-2022 pull request #7
Opened 2022-03-10 00:49 UTC by sql3

2022-03-10 08:30 UTC, AbdullinAM commented
В названии PR нужно было указать название задачи

2022-03-10 08:48 UTC, AbdullinAM requested changes

2022-03-10 08:48 UTC, AbdullinAM commented on app/src/main/java/programming/task1/PriceList.java
> +    private final Map<Integer, NameAndPrice> list = new HashMap<>();
Называть мапу `list` не очень хорошая идея

2022-03-10 08:48 UTC, AbdullinAM commented on app/src/main/java/programming/task1/PriceList.java
> +class NameAndPrice {
Название, опять таки, не очень удачное

2022-03-10 08:48 UTC, AbdullinAM commented on app/src/main/java/programming/task1/PriceList.java
> +    public Map<Integer, NameAndPrice> getList() {
Давать внешним пользователям доступ к mutable внутренностям вашего объекта -- не очень хорошая идея.

2022-03-10 08:48 UTC, AbdullinAM commented on app/src/main/java/programming/task1/PriceList.java
> +    public void setName(String name) {
В своем коде вы используете свой класс как immutable структуру, что хорошо. Но тогда можно его сделать immutable чтобы не возникало неожиданных проблем

2022-03-10 08:48 UTC, AbdullinAM commented on app/src/test/java/programming/task1/PriceListTest.java
> +        assertTrue(list.replacePrice(15, 93.0));
После изменения цены стоит еще проверить что она действительно поменялась

2022-03-10 08:48 UTC, AbdullinAM commented on app/src/test/java/programming/task1/PriceListTest.java
> +        assertTrue(list.replaceName(15, "Кефир"));
Тут тоже: если вы что-то поменяли, надо проверить что оно поменялось

2022-03-10 08:48 UTC, AbdullinAM commented on app/src/test/java/programming/task1/PriceListTest.java
> +        assertFalse(list.deleteProduct(56));
То же самое: если удалили, то проверьте что товара больше нет

2022-03-10 12:23 UTC, sql3 commented on app/src/test/java/programming/task1/PriceListTest.java
> +        assertFalse(list.deleteProduct(56));
Насчет этого, тут программа выдаст false, так как такого кода нет в мапе, он и не должен удалиться, его и так нет

2022-03-10 12:41 UTC, AbdullinAM commented on app/src/test/java/programming/task1/PriceListTest.java
> +        assertFalse(list.deleteProduct(56));
Этот комментарий относился не конкретно к этой строчке, а ко всему тесту

2022-03-14 08:31 UTC, AbdullinAM commented
Задание зачтено с оценкой 5

2022-03-14 08:31 UTC, closed without merging